---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 58dc8ed3d14eec66ff6366f71e7a8551c21a69b3
    app.quarkus.io/build-timestamp: 2023-12-18 - 14:12:19 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: expense-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: expense-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: expense-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 58dc8ed3d14eec66ff6366f71e7a8551c21a69b3
    app.quarkus.io/build-timestamp: 2023-12-18 - 14:12:19 +0000
  labels:
    app.kubernetes.io/name: expense-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: expense-service
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: expense-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: openjdk-17
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-17
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 58dc8ed3d14eec66ff6366f71e7a8551c21a69b3
    app.quarkus.io/build-timestamp: 2023-12-18 - 14:12:19 +0000
  labels:
    app.kubernetes.io/name: expense-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: expense-service
spec:
  output:
    to:
      kind: ImageStreamTag
      name: expense-service:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-17:1.14
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 58dc8ed3d14eec66ff6366f71e7a8551c21a69b3
    app.quarkus.io/build-timestamp: 2023-12-18 - 14:12:19 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: expense-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: expense-service
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: expense-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 58dc8ed3d14eec66ff6366f71e7a8551c21a69b3
        app.quarkus.io/build-timestamp: 2023-12-18 - 14:12:19 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: expense-service
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: student/expense-service:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: expense-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - expense-service
        from:
          kind: ImageStreamTag
          name: expense-service:1.0.0-SNAPSHOT
      type: ImageChange
